version: '3'
services:
  web:
    image: react-redux-chat-app
    build: .
    ports:
     - "3000:3000"
    depends_on: 
      - "mongodb"
  mongodb:
    image: "mongo:latest"
    ports: 
     - "27017:27017"
 